name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'app/**'

jobs:
  build-and-push-to-ECR:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout app code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set Image Tag
      run: echo "IMAGE_TAG=${{ secrets.ECR_REPOSITORY }}:latest" >> $GITHUB_ENV

    - name: Build, tag, and push Docker image to ECR
      run: |
        docker build -t ${{ env.IMAGE_TAG }} -f Dockerfile ./app
        docker push ${{ env.IMAGE_TAG }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_TAG }}'
        exit-code: '1'
        format: 'table'
        severity: 'CRITICAL,HIGH'

    - name: Push Docker image to ECR
      run: |
        docker push ${{ env.IMAGE_TAG }}
        echo "Docker image pushed to ECR: ${{ env.IMAGE_TAG }}"