name: Terraform Apply

on:
  push:
    paths:
      - 'terraform/**'
    

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download terraform.tfvars from S3
        working-directory: terraform
        run: |
            aws s3 cp s3://threat-composer-project/terraform.tfvars ./

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init 

      - name: Terraform Format and Validate
        working-directory: terraform
        run: |
          terraform fmt  
          terraform validate

      - name: Setup Tflint
        uses: terraform-linters/setup-tflint@v4
        with: 
          tflint_version: latest

      
      - name: TFLint Scan
        working-directory: terraform
        run: tflint -f compact

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          skip_check: CKV_AWS_131,CKV_AWS_290,CKV_AWS_355,CKV2_AWS_28,CKV_AWS_260,CKV_AWS_23,CKV2_AWS_11,CKV2_AWS_38,CKV2_AWS_39,CKV2_AWS_5,CKV2_AWS_19,CKV2_AWS_12,CKV_AWS_91,CKV_AWS_150

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan