name: Terraform Apply

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'tf-plan') ||
      github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download terraform.tfvars from S3
        run: aws s3 cp s3://threat-composer-project/terraform.tfvars ./terraform/

      - name: Download artifact from tf-plan workflow
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'tf-plan.yml'
          workflow_conclusion: 'success'
          name: tfplan
          path: ./terraform/

      - name: Check for tfplan artifact
        run: |
          if [ ! -f ./terraform/tfplan ]; then
            echo "tfplan artifact does not exist."
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan





