name: Terraform Apply

on:
  pull_request:
    types:
      - closed
    branches:
      - main  
  workflow_dispatch:

jobs:
  terraform-apply:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'tf-plan') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download terraform.tfvars from S3
        run: aws s3 cp s3://threat-composer-project/terraform.tfvars ./

      - name: Download Terraform Plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Check for tfplan artifact
        run: |
          if [ ! -f ./terraform/tfplan ]; then
            echo "tfplan does not exist."
            exit 1
          fi

      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform/tfplan


